### ISSUE TITLE
Emote Utility hover glitch

### ISSUE THREAD

**Issue by ezist** [TrueXPixels/powercord-reverse-image-search#2]
## Description:
When using Emote Utility along with Reverse Image Search, hovering over either's submenu item will act as if you're hovering over the other one as well.  
This is probably because the two have the same IDs for their item elements, `message-item-0-0-1`.

## Screenshot:
![DiscordCanary_UrCmeYvwIR](https://user-images.githubusercontent.com/50839590/93660419-4a3ca600-fa14-11ea-8382-f0209556f39d.png)

**Comment by TrueXPixels** [comment]
Possibly fixed (0320847)
