### ISSUE TITLE
Use TinEye instead of Google.

### ISSUE THREAD

**Issue by NotExactlyMeButMeh** [TrueXPixels/powercord-reverse-image-search#3]
TinEye would be a preferred option to Google for reverse image searching, perhaps add a setting for choosing your search engine of choice, especially since I would rather that my search data not be directly collected by Google themselves.

[Link to TinEye](https://tineye.com/)

**Comment by ezist** [comment]
My pull request adds a sub-menu, and has TinEye as an option. #1

**Comment by TrueXPixels** [comment]
Added by @ezist in #1
